apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatapp
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    # No host makes this rule match the VM public IP as well as a domain name.
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chatapp
                port:
                  number: 80
