apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
type: Opaque
stringData:
  JWT_SECRET: replace-with-a-long-random-secret
  MONGODB_URI: mongodb+srv://prakashkumargautam21_db_user:Suresh981@mongobd.7gfxd22.mongodb.net/?appName=mongobd
